apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

configMapGenerator:
  - name: app-config
    envs:
      - config.env
    behavior: replace

labels:
  - pairs:
      environment: prod

patches:
  - path: patch.yaml
    target:
      kind: Deployment
      name: mydeployment
