apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mypod.yaml
  - mydeployment.yaml

configMapGenerator:
  - name: app-config
    envs:
      - config.env

labels:
  - pairs:
      app: nginx

images:
  - name: nginx
    newTag: "1.28"
